openapi: 3.0.3
info:
  title: News Feed Server
  version: 0.1.0
servers:
  - url: http://localhost:8001/
paths:
  /search:
    get:
      summary: Request to search for articles
      operationId: search
      parameters:
        - name: query
          in: query
          description: Search query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SearchResult"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /topic:
    get:
      summary: Request to get articles by topic
      operationId: topic
      parameters:
        - name: topic
          in: query
          description: Topic of the article
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SearchResult"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          example: "Error message"
      required:
        - message
    SearchResult:
      type: object
      properties:
        title:
          type: string
          example: "Article title"
        url:
          type: string
          example: "https://example.com/article"
        content:
          type: string
          example: "Article content here"
      required:
        - title
        - url
        - content