openapi: 3.1.3
info:
  title: Smart Article Analyzer
  description: Text Analysis Application
  version: 0.0.1
servers:
  - url: http://localhost:8080/api
paths:
  /analyze:
    post:
      summary: Request to analyze text
      operationId: analyze
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Content"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Analysis"
components:
  schemas:
    Content:
      type: object
      properties:
        text:
          type: string
          example: "Text here"
      required:
        - text
    Analysis:
      type: object
      properties:
        text:
          type: string
          example: "Summary here"
        keywords:
          type: array
          items:
            type: string
            example: "keyword"
        polarity:
          type: boolean
          example: 2.5
      required:
        - text
        - keywords
        - polarity